### ISSUE TITLE
It isn't working on my computer....The color doesn't change

### ISSUE THREAD

**Issue by betty35** [johsund/ColorStyler#1]
![image](https://cloud.githubusercontent.com/assets/17248038/19434599/f906af0e-9498-11e6-8ed4-1c207be1fd1c.png)

I'm working with Qlik Sense Desktop. When I selected a theme, nothing changed in the preview. Then I clicked save changes several times and it said 'Success! Application has been saved.', but nothing other than that happened. I also tried refreshing the page. Nothing happened. The color selecting page is cool and all but the color of my object isn't changing... Q_Q

**Comment by johsund** [comment]
Hi betty,

Well that's not great. Is it a small and non-sensitive app that you can shar so I can test it on my end?

**Comment by betty35** [comment]
Actually, not only that one. It doesn't work on other apps too. I'm not sure if it has something to do with the specific object. Maybe I did something wrong on the installation? Is there some other configurations need to be done other than unzip it to qlik sense extension folder and open http://localhost:4848/extensions/colorstyler/colorstyler.html?

[map123.txt](https://github.com/johsund/ColorStyler/files/533592/map123.txt)
I changed the suffix to txt. Just change it back to .qvf later

**Comment by johsund** [comment]
Aah, thanks for that. 
Found an issue in point map gradient coloring when using a "handwritten" i.e. non library measure.

I've updated the code. Please try pulling the extension again and see if it's fine on your end as well!

**Comment by betty35** [comment]
You are so amazingly fast 0.0... I'll try it tomorrow. Off work right now. App's in company's computer. And thanks again for this great extension and your help!

**Comment by betty35** [comment]
I can make it work now! Although it is still kind of weird. I have to add the map into master object, select a theme in the extension (now the points turns all gray...and in app, the color is switched to 'by expression' with no expression in it), unlink visualization of the map, select single color, by measure, by dimension, by measure, finally back to by expression, and the color expression magically appears and everything becomes fine.

**Comment by johsund** [comment]
Hi Betty, I think there's some little setting missing on my end. I can't seem to recreate it though and need your help. Please see attached video from my end. Are you creating your map differently? Or selecting something different in colorstyler?

Video link:
https://youtu.be/KG_vNzjcQxc

**Comment by betty35** [comment]
![image](https://cloud.githubusercontent.com/assets/17248038/19467590/8a27c760-9544-11e6-9cec-c1c26d8ead46.png)
Happened to the demo too. 

The differences I can think of:
1. I selected 'by measure', not auto or single color for the object before using the colorstyler. (Tried, not working)
2. The data used in dimension and measure are actually not in the same table (one table for latitude , longitude and city names, and another for measures and city names)
3. The measure is an expression like sum(XXX)

**Comment by johsund** [comment]
![qlikcolorstyler](https://cloud.githubusercontent.com/assets/14173263/19468173/8b27d012-9547-11e6-9e06-ceae5e0de3fa.png)

That's very strange. I tried the same demo app and it seems to work fine.
Which version of Qlik Sense desktop are you using?

**Comment by betty35** [comment]
![image](https://cloud.githubusercontent.com/assets/17248038/19468566/a23ead8c-9549-11e6-8c0a-5934439d6b3a.png)

**Comment by johsund** [comment]
Hi Betty, not quite sure why it's not working for you (I'm using 3.1.1 by the way so you might want to try updating). Do you think you can create another app with a visualization that's not working and upload so that I can give it a shot?

**Comment by betty35** [comment]
I think I'll just update it...or a field in the tool to show color expressions for copy&paste? The app I uploaded yesterday is not working on my computer too, actually.

**Comment by betty35** [comment]
Updated Qlik Sense to v3.1. Works fine with Chrome~but not really with IE 11.0.9... May have something to do with browsers or their security settings.

**Comment by Eason123456** [comment]
Hi,there is also something wrong on my computer。Why can't I find the objects,of course ,l created the app.

**Comment by Eason123456** [comment]
Hi,there is also something wrong on my computer。Why can't I find the objects,of course ,l created the app.
![image](https://cloud.githubusercontent.com/assets/23250682/19997034/a5363e30-a29e-11e6-9656-7f594160e0b1.png)

**Comment by johsund** [comment]
Hi Eason, please check that you have created Master Objects. After you create a visualization in the app, please add it to the master library and give it a name. Then it should show up in the ColorStyler.
