### ISSUE TITLE
app selection drop down does not displays the apps

### ISSUE THREAD

**Issue by srinibs** [johsund/ColorStyler#10]
I had recently downloaded your extension.  after hitting the required url, i am able to see the rendering of the HTML page, but i do not see the list of app from the dropdown selection.

I had kept open my desktop version of qliksense and also i was able to navigate to the dev-hub and see the list of apps appearing in various options. Hence, definitely the qlik engine is running, but some how i am unable to see the list of apps using the colostyler html page.

Can you please help.

Srini

**Comment by johsund** [comment]
Hi Srini - please use Qlik Feb 2018 release and the new color styler Theme instead of the old extension:
https://github.com/johsund/ColorStyler/blob/master/colorStylerTheme.zip?raw=true

**Comment by srinibs** [comment]
Hi,
Thanks for the prompt reply. Tried the above with Feb 2018 release and it
works like a charm.

Thanks
Srinivasan S
