### ISSUE TITLE
Color Styler Broke My App?!

### ISSUE THREAD

**Issue by dustinbaxa** [johsund/ColorStyler#2]
Hi! I've used the color styler the past few days and it worked great. However, I just tried using it on a new app that I just built and something strange is going on. I went to the color styler, selected the master item (which was a map), and selected a gradient. Once I did that, I got the spinning wheel that will not go away.  I did not hit Save changes. Unfortunately, when I open that app most of my visualizations show the spinning wheel, all of the extensions that I used in that app are spinning wheel, and none of the fields or master items are showing (again, spinning wheel). My engine service just keeps running too! Any idea how to fix this? I am using Sense Enterprise 3.1.1

--update: If I delete the object (map) that I originally tried to access through Color Styler, the app works fine. But if I drag in the master item again then the object never loads (spinning wheel).

**Comment by johsund** [comment]
Hi Dustin, any chance you can recreate this in a simple app with just the map and attach to this issue? Would love to take a look and see if it's something I'm missing. Thx

**Comment by dustinbaxa** [comment]
Hello! I have attached the app. The map on the left is the master item for you to test, the map on the right is just a copy of it. Once I select gradient theme or gradient, the visualization spins in the color picker and my app (my app is broken immediately because the changes take effect right away, as noted in my other issue logged).

[Situational Awareness.zip](https://github.com/johsund/ColorStyler/files/575907/Situational.Awareness.zip)

**Comment by johsund** [comment]
Hi Dustin, thanks for uploading an example app. I'm able to recreate the issue using the app you attached. I can't seem to get the same issue with another app though which is a bit odd. 
There's multiple permutations that are possible: using a library dimension or field as dimension, using a library measure or expression for size, using a library measure or expression for color. When I look at the color expression that gets generated it looks perfectly fine to me bit when I use it for the map it seems to just spin. I'll need a bit more time to figure that one out I think. Let me know if you find out any interesting facts around this. Thanks

**Comment by johsund** [comment]
Hi Dustin, now that Qlik Sense February 2018 has been released, please use the new color styler Theme that includes all the styling options in a native structure: https://github.com/johsund/ColorStyler/blob/master/colorStylerTheme.zip?raw=true
