### ISSUE TITLE
Changes are saved without hitting Save Changes

### ISSUE THREAD

**Issue by dustinbaxa** [johsund/ColorStyler#3]
When selecting different colors, the changes are made and saved (and thus reflected in the app) without having to click Save Changes. I am using 3.1.1 Sense Enterprise.

**Comment by johsund** [comment]
Hi Dustin, your user session is shared so if you have the app open in the normal Qlik Sense client + edit a visualization in ColorStyler at the same time, you will see the changes in the app. ColorStyler is not saving the app until you click the Save button though. The Qlik Sense client will autosave the app (by default every 30 seconds) as seen from the help: http://help.qlik.com/en-US/sense/3.1/Subsystems/ManagementConsole/Content/engines-overview.htm

**Comment by dustinbaxa** [comment]
Thanks for the quick response. I just tested this and I am seeing different behavior. If I launch color picker and quickly make a selection and then close out of Color Picker, it is saved (the process takes about 5 minutes). For me, the changes are being saved immediately.
