### ISSUE TITLE
Issue on coloring combo charts with grouped bars...

### ISSUE THREAD

**Issue by betty35** [johsund/ColorStyler#4]
![image](https://cloud.githubusercontent.com/assets/17248038/20037352/f4107d20-a458-11e6-81d5-0849a2a348d5.png)
... ...

**Comment by johsund** [comment]
Hi Betty, there's no good way to write a color expression when dealing with multiple measures that I'm aware of so can't really help you here. Any idea on how you would color it with an expression, please let me know. Thanks!
