### ISSUE TITLE
ColorStyler blank page when selecting the app

### ISSUE THREAD

**Issue by midin** [johsund/ColorStyler#5]
Hi,

I was really eager to try the ColorStyler extension but I’m always done with this result, nevermind the selected app or browser used. Could you please help me?

Thanks
Miroslav

![image](https://cloud.githubusercontent.com/assets/745954/23166235/1e167eea-f840-11e6-953b-1e5f64ea73aa.png)

**Comment by johsund** [comment]
Hi Miroslav,

Make sure you add objects to your master library in your qlik app. Only master objects will show up in Color styler. Right click one of your charts in edit mode and you will be able to add it to the master objects.

Best regards,
Johannes

Sent from my iPhone

On 21 Feb 2017, at 8:17 PM, midin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I was really eager to try the ColorStyler extension but I’m always done with this result, nevermind the selected app or browser used. Could you please help me?

Thanks
Miroslav

[image]<https://cloud.githubusercontent.com/assets/745954/23166235/1e167eea-f840-11e6-953b-1e5f64ea73aa.png>

**Comment by midin** [comment]
Thanks, that we the problem!
Miroslav
