### ISSUE TITLE
Connection Lost Error

### ISSUE THREAD

**Issue by andrewrreed** [johsund/ColorStyler#8]
I receive this error for every app I try to access. All are refreshed and running properly..

![colorstylerissue](https://user-images.githubusercontent.com/23462538/32609011-276e4aea-c52c-11e7-95da-f2311e3a101b.png)

**Comment by Florian95** [comment]
Same here. How can we help ?

**Comment by johsund** [comment]
Hi guys, just to check. After clicking "Close" is it actually connected to the app and allow you to click on one of your master apps and style it?
Seems to be the case for me with September 2017. Trying to figure out why the error message pops up (seems to be a websocket connection being closed), but after clicking Close I can still use the app interestingly.

**Comment by andrewrreed** [comment]
Nope - once I click on "Close" it is simply a blank screen (unable to see or select anything). Thanks for the help.

**Comment by andrewrreed** [comment]
Have you had the chance to look further into this?

**Comment by jdmarlin** [comment]
Extension bugs out for me at this line:

`app = qlik.openApp($(this).val(), config);`

Using Qlik Sense February 2018

**Comment by johsund** [comment]
Hi guys,

I've converted the whole extension into a Theme for it to work nicer with February 2018. Please download here: https://github.com/johsund/ColorStyler/blob/master/colorStylerTheme.zip?raw=true
