### ISSUE TITLE
Colorstyler not loading correctly after September 2017 release update

### ISSUE THREAD

**Issue by SamboGitHub** [johsund/ColorStyler#9]
We recently upgraded to the September 2017 release.  Since then, when trying to load an application, the pop- up displays the following:

An error occurred
Connection lost. Make sure that Qlik Sense is running properly. If your session has timed out due to inactivity, refresh to continue working.

Hitting cancel allows you to use Colorstyler, reload continues to display the same error.

Thanks

**Comment by johsund** [comment]
Hi Sambo,

Please use Qlik Sense February 2018 release and the new color styler Theme with all the relevant color options: https://github.com/johsund/ColorStyler/blob/master/colorStylerTheme.zip?raw=true
